# Generated by Django 6.0 on 2025-12-11 14:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(help_text='Format: DEV-YYYY-###', max_length=20, unique=True, verbose_name='Numéro de devis')),
                ('total_labor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name="Total Main d'Œuvre HT (€)")),
                ('total_parts', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total Pièces HT (€)')),
                ('total_ht', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total HT (€)')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('0.20'), help_text='Ex: 0.20 pour 20%', max_digits=4, verbose_name='Taux TVA')),
                ('total_vat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant TVA (€)')),
                ('total_ttc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total TTC (€)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'émission")),
                ('validity_date', models.DateField(help_text="Date limite d'acceptation (+15 jours)", verbose_name='Date de validité')),
                ('is_validated_by_manager', models.BooleanField(default=False, help_text='Verrouillé après validation gestionnaire (BF27)', verbose_name='Validé par gestionnaire')),
                ('is_accepted_by_client', models.BooleanField(default=False, help_text='Client a accepté le devis (BF44)', verbose_name='Accepté par le client')),
                ('is_refused_by_client', models.BooleanField(default=False, verbose_name='Refusé par le client')),
                ('refusal_reason', models.TextField(blank=True, help_text='Motif optionnel si refusé (BF45)', verbose_name='Motif de refus')),
                ('acceptance_date', models.DateTimeField(blank=True, null=True, verbose_name="Date d'acceptation")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quote', to='cases.case', verbose_name='Dossier')),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_type', models.CharField(choices=[('LABOR', "Main d'œuvre"), ('PARTS', 'Pièces')], max_length=10, verbose_name='Type de ligne')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('hours', models.DecimalField(blank=True, decimal_places=2, help_text="Nombre d'heures de main d'œuvre", max_digits=5, null=True, verbose_name='Heures')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Taux horaire (€/h)')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité')),
                ('unit_price_ht', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Prix unitaire HT (€)')),
                ('total_ht', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total HT (€)')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='quotes.quote', verbose_name='Devis')),
            ],
            options={
                'verbose_name': 'Ligne de Devis',
                'verbose_name_plural': 'Lignes de Devis',
                'ordering': ['line_type', 'id'],
            },
        ),
    ]
