# Generated by Django 6.0 on 2025-12-11 14:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaultGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du groupe')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, help_text='Icône CSS (ex: fa-car)', max_length=50, verbose_name='Icône')),
                ('order', models.IntegerField(default=0, help_text="Ordre d'affichage", verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
            ],
            options={
                'verbose_name': 'Groupe de Pannes',
                'verbose_name_plural': 'Groupes de Pannes',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('60.00'), help_text="Taux horaire de main d'œuvre en euros", max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))], verbose_name='Taux horaire (€/h)')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('0.20'), help_text='Taux de TVA (ex: 0.20 pour 20%)', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Taux de TVA')),
                ('quote_validity_days', models.IntegerField(default=15, help_text="Nombre de jours de validité d'un devis", validators=[django.core.validators.MinValueValidator(1)], verbose_name='Validité devis (jours)')),
                ('appointment_cancel_hours', models.IntegerField(default=24, help_text='Délai minimum (en heures) pour annuler/modifier un RDV', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Délai annulation RDV (h)')),
                ('quote_variation_threshold', models.DecimalField(decimal_places=2, default=Decimal('0.10'), help_text='Seuil de variation pour notification (ex: 0.10 pour 10%)', max_digits=3, verbose_name='Seuil variation devis')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
            ],
            options={
                'verbose_name': 'Paramètres Système',
                'verbose_name_plural': 'Paramètres Système',
            },
        ),
        migrations.CreateModel(
            name='Fault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la panne')),
                ('description', models.TextField(blank=True, verbose_name='Description détaillée')),
                ('labor_hours', models.DecimalField(decimal_places=2, help_text="Temps de main d'œuvre en heures (ex: 1.5)", max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Heures de MO')),
                ('parts_name', models.CharField(blank=True, max_length=200, verbose_name='Nom de la pièce')),
                ('parts_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Coût des pièces en euros', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Coût pièces (€)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faults', to='catalog.faultgroup', verbose_name='Groupe')),
            ],
            options={
                'verbose_name': 'Panne (Sous-catégorie)',
                'verbose_name_plural': 'Pannes (Sous-catégories)',
                'ordering': ['group__order', 'group__name', 'name'],
                'unique_together': {('group', 'name')},
            },
        ),
    ]
