# Generated by Django 6.0 on 2025-12-11 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_recurring', models.BooleanField(default=False, help_text='Créneau récurrent (chaque semaine)', verbose_name='Récurrent')),
                ('weekday', models.IntegerField(blank=True, choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], help_text='Pour les créneaux récurrents', null=True, verbose_name='Jour de la semaine')),
                ('date', models.DateField(blank=True, help_text='Pour un créneau ponctuel (non récurrent)', null=True, verbose_name='Date spécifique')),
                ('start_time', models.TimeField(verbose_name='Heure de début')),
                ('end_time', models.TimeField(verbose_name='Heure de fin')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('is_exception', models.BooleanField(default=False, help_text='Jour férié ou fermeture exceptionnelle', verbose_name='Exception')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Créneau de RDV',
                'verbose_name_plural': 'Créneaux de RDV',
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date du RDV')),
                ('start_time', models.TimeField(verbose_name='Heure de début')),
                ('end_time', models.TimeField(verbose_name='Heure de fin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de réservation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='Annulé')),
                ('cancellation_date', models.DateTimeField(blank=True, null=True, verbose_name="Date d'annulation")),
                ('cancellation_reason', models.TextField(blank=True, verbose_name="Motif d'annulation")),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='cases.case', verbose_name='Dossier')),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
