# Generated by Django 6.0 on 2025-12-12 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Description détaillée du problème rencontré', verbose_name='Description du problème')),
                ('urgency_level', models.CharField(choices=[('BASSE', 'Basse'), ('NORMALE', 'Normale'), ('HAUTE', 'Haute')], default='NORMALE', max_length=10, verbose_name="Niveau d'urgence")),
                ('status', models.CharField(choices=[('NOUVEAU', 'Nouveau'), ('DEVIS_EMIS', 'Devis émis'), ('DEVIS_ACCEPTE', 'Devis accepté'), ('DEVIS_REFUSE', 'Devis refusé'), ('RDV_CONFIRME', 'RDV confirmé'), ('EN_COURS', 'En cours'), ('PRET', 'Prêt'), ('CLOTURE', 'Clôturé'), ('EXPIRE', 'Expiré')], default='NOUVEAU', max_length=20, verbose_name='Statut')),
                ('estimated_completion', models.DateTimeField(blank=True, help_text='Date et heure estimée de fin de réparation', null=True, verbose_name='Estimation de fin (ETA)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('faults', models.ManyToManyField(blank=True, help_text='Pannes déclarées par le client', related_name='cases', to='catalog.fault', verbose_name='Pannes sélectionnées')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='vehicles.vehicle', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Dossier',
                'verbose_name_plural': 'Dossiers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=20, verbose_name='Ancien statut')),
                ('new_status', models.CharField(max_length=20, verbose_name='Nouveau statut')),
                ('comment', models.TextField(blank=True, verbose_name='Commentaire')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='cases.case', verbose_name='Dossier')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Log de Statut',
                'verbose_name_plural': 'Logs de Statuts',
                'ordering': ['changed_at'],
            },
        ),
    ]
