# Generated by Django 5.2.7 on 2025-12-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0002_vehicle_fuel_type_vehicle_mileage_vehicle_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('MOTOR', 'Moteur'), ('BRAKES', 'Freinage'), ('ELECTRIC', 'Électricité'), ('TIRES', 'Pneus'), ('FLUIDS', 'Fluides'), ('OTHER', 'Autres')], max_length=20)),
                ('labor_time', models.FloatField(help_text="Temps de main-d'œuvre en heures")),
                ('labor_price', models.FloatField(default=60)),
                ('parts_cost', models.FloatField(default=0)),
            ],
        ),
    ]
