# Generated by Django 5.2.7 on 2025-12-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0003_fault'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fault',
            name='labor_time',
            field=models.FloatField(),
        ),
    ]
