# Generated by Django 5.2.7 on 2025-12-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0004_alter_fault_labor_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fault',
            name='category',
        ),
        migrations.AlterField(
            model_name='fault',
            name='labor_time',
            field=models.FloatField(default=1),
        ),
    ]
