# Generated by Django 5.2.7 on 2025-12-11 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0005_remove_fault_category_alter_fault_labor_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='VehicleAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('PHOTO', 'Photo ou Image'), ('NOTE', 'Note Textuelle')], default='NOTE', max_length=10, verbose_name='Type de contenu')),
                ('file', models.FileField(blank=True, null=True, upload_to='vehicle_assets/', verbose_name='Fichier')),
                ('note_content', models.TextField(blank=True, max_length=500, null=True, verbose_name='Contenu de la note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='garage.vehicle', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Pièce Jointe de Véhicule',
                'verbose_name_plural': 'Pièces Jointes de Véhicule',
                'ordering': ['-created_at'],
            },
        ),
    ]
