# Generated by Django 6.0 on 2025-12-11 14:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text='2-50 caractères', max_length=50, verbose_name='Marque')),
                ('model', models.CharField(help_text='2-50 caractères', max_length=50, verbose_name='Modèle')),
                ('year', models.IntegerField(help_text='Entre 1950 et année courante', validators=[django.core.validators.MinValueValidator(1950, message="L'année doit être supérieure à 1950"), django.core.validators.MaxValueValidator(2025, message="L'année ne peut pas être dans le futur")], verbose_name='Année')),
                ('plate_number', models.CharField(blank=True, help_text='Format: AA-123-AA (optionnel si surnom fourni)', max_length=20, null=True, validators=[django.core.validators.RegexValidator(code='invalid_plate', message='Format invalide. Utiliser: AA-123-AA', regex='^[A-Z]{2}-[0-9]{3}-[A-Z]{2}$')], verbose_name='Immatriculation')),
                ('nickname', models.CharField(blank=True, help_text="Obligatoire si pas d'immatriculation, 2-30 caractères (ex: 'Voiture principale')", max_length=30, verbose_name='Surnom du véhicule')),
                ('mileage', models.IntegerField(help_text='Entre 1 et 999 999', validators=[django.core.validators.MinValueValidator(1, message='Le kilométrage doit être positif'), django.core.validators.MaxValueValidator(999999, message='Le kilométrage maximum est 999 999 km')], verbose_name='Kilométrage (km)')),
                ('fuel_type', models.CharField(blank=True, choices=[('ESSENCE', 'Essence'), ('DIESEL', 'Diesel'), ('ELECTRIQUE', 'Électrique'), ('HYBRIDE', 'Hybride'), ('GPL', 'GPL'), ('AUTRE', 'Autre')], help_text='Diesel, Essence, Électrique, Hybride, etc.', max_length=50, verbose_name='Type de carburant')),
                ('last_technical_inspection', models.DateField(blank=True, help_text="Format: JJ/MM/AAAA, ne peut pas être dans le futur de plus d'un an", null=True, verbose_name='Date du dernier contrôle technique')),
                ('insurance_company', models.CharField(blank=True, help_text='Max 100 caractères', max_length=100, verbose_name="Nom de l'assurance")),
                ('insurance_expiry_date', models.DateField(blank=True, help_text='Format: JJ/MM/AAAA', null=True, verbose_name="Date d'échéance de l'assurance")),
                ('notes', models.TextField(blank=True, help_text='Informations additionnelles', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('is_active', models.BooleanField(default=True, help_text='Suppression logique', verbose_name='Actif')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'événement")),
                ('event_type', models.CharField(choices=[('CREATION', 'Création du véhicule'), ('MODIFICATION', 'Modification'), ('DELETE', 'Suppression (Désactivation)'), ('ACTIVATION', 'Activation'), ('CASE_CREATED', 'Nouveau dossier'), ('QUOTE_GENERATED', 'Devis généré'), ('REPAIR_COMPLETED', 'Réparation terminée'), ('OTHER', 'Autre')], default='OTHER', max_length=50, verbose_name="Type d'événement")),
                ('description', models.TextField(verbose_name='Description')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='vehicles.vehicle', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Historique Véhicule',
                'verbose_name_plural': 'Historiques Véhicules',
                'ordering': ['-event_date'],
            },
        ),
    ]
